### ISSUE TITLE
Inscription au site

### ISSUE THREAD

**Issue by KraTuX31** [FishAndFriends/FishAndFriends#1]
**En tant que** _utilisateur non inscrit_
**Je souhaite** _m’inscrire au site_
**Afin de** _profiter des fonctionnalités du réseau social_

**Comment by meGAmeS1** [comment]
Sécurisation du mot de passe : https://grails-plugins.github.io/grails-spring-security-core/guide/passwords.html
Pour les emails on verra plus tard mais on peut se pencher là-dessus : https://grails.org/plugin/mail
