### ISSUE TITLE
Score des pêcheur

### ISSUE THREAD

**Issue by KraTuX31** [FishAndFriends/FishAndFriends#14]
**En tant que** _utilisateur connecté_
**Je souhaite** _connaître le score d’un autre pêcheur_
**Afin de** _évaluer le niveau du pêcheur_

**Comment by meGAmeS1** [comment]
- Nombre de prises
- Taille moyenne
- Poids moyen

**Comment by jochy** [comment]
Backend implémenté et testé à 100%

**Comment by jochy** [comment]
commit : e98baa1627ee69d5f51d8d44ec600055524a588a
