### ISSUE TITLE
Création de nouveaux lieux de pêche

### ISSUE THREAD

**Issue by KraTuX31** [FishAndFriends/FishAndFriends#3]
**En tant que** _utilisateur connecté_
**Je souhaite** _pouvoir créer de nouveaux lieux de pêche_
**Afin de** _faire partager aux autres utilisateurs_

**Comment by meGAmeS1** [comment]
Pour la sélection d'un lieu sur G-Maps : http://www.wimagguc.com/2013/06/jquery-latitude-and-longitude-picker-gmaps/
