### ISSUE TITLE
Recherche de lieux de pêches

### ISSUE THREAD

**Issue by KraTuX31** [FishAndFriends/FishAndFriends#5]
**En tant que** _utilisateur connecté_
**Je souhaite** _pouvoir trouver des lieux de pêche_
**Afin de** _découvrir de nouveaux lieux à proximité_

**Comment by KraTuX31** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/6813065/10269997/4e0f553e-6ae5-11e5-818c-c04d586b8b07.jpg)

**Comment by D0oM** [comment]
TODO : Test  service  + modifier placeholder du param quand la vue sera créer
